Feature/t 22
martkvam/bacheloroppgave pull request #8
Opened 2022-03-07 10:37 UTC by martkvam

Nå skal naming server, gateway og case-service fungere. Frontend kan nå sende alle requests til gateway (port 8080).

2022-03-07 10:50 UTC, martkvam commented
Lagt til docker-compose i workflow slik at testene ikke feiler lenger (servicen er avhengig av databasen for å kjøre).

2022-03-07 12:20 UTC, martkvam commented
![](https://github.trello.services/images/mini-trello-icon.png) [Legge til CORS i API-gateway](https://trello.com/c/g9sOS43r/22-legge-til-cors-i-api-gateway)

2022-03-07 13:03 UTC, trymstenberg requested changes
Fjerne dependency som ikke brukes

2022-03-08 12:14 UTC, trymstenberg approved these changes

2022-03-08 12:15 UTC, merged